# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicial', models.DateField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueos.Parqueo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tipos',
            name='vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueos.Vehiculos'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='transportes',
            field=models.ManyToManyField(through='parqueos.Tipos', to='parqueos.Vehiculos'),
        ),
    ]
